### ISSUE TITLE
`sqlDropComposite` should take `CompositeType` as input

### ISSUE THREAD

**Issue by jonathanjouty** [scrive/hpqtypes-extras#25]
Currently we have
```hs
sqlCreateComposite :: CompositeType -> RawSQL ()
sqlDropComposite :: RawSQL () -> RawSQL ()
```

It is simple enough to write `sqlDropComposite (ctName yourComposite)` but it is an inconsistent and more error-prone interface.

Why not take `CompositeType` instead?

**Comment by jonathanjouty** [comment]
@arybczak any reason for doing things this way? or simply an oversight?

**Comment by arybczak** [comment]
That's intentional. As explanation consider old version of `sqlDropCheck` - it used to take a `Check` and people were passing `Check` objects with nonsensical values other than its name (because only the name was needed to remove the check), that's why `sqlDropCheck` now only takes a name and why `sqlDropComposite` is the same.

**Comment by jonathanjouty** [comment]
Right—I see the use-case now, where you have removed the actual type from your code and you want to drop it from database.

Thanks.
